### ISSUE TITLE
code not compiling

### ISSUE THREAD

**Issue by keough99** [StarQuestMinecraft/StarQuestCode#4]
hello im trying to compile the source code and get the plugins working but the source code wont compile no matter what i try?
(ik you may not help but this might be a source code issue and some documentation on the java version etc woud be helpful)

**Comment by evanaesarcaesar** [comment]
This is not a source code issue, many people have successfully downloaded and compiled our code. We're categorically not providing assistance with the use of our code, but you can ask players in the community for help and they might
